# Generated by Django 3.2.19 on 2023-11-15 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vyaparapp', '0010_auto_20231106_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=100, null=True)),
                ('orderdate', models.DateField(null=True)),
                ('duedate', models.DateField(null=True)),
                ('placeofsupply', models.CharField(max_length=100, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=100)),
                ('UPI', models.CharField(max_length=100, null=True)),
                ('checkno', models.CharField(max_length=100, null=True)),
                ('subtotal', models.CharField(max_length=100, null=True)),
                ('IGST', models.CharField(max_length=100, null=True)),
                ('CGST', models.CharField(max_length=100, null=True)),
                ('SGST', models.CharField(max_length=100, null=True)),
                ('taxamount', models.CharField(max_length=100, null=True)),
                ('adjustment', models.CharField(max_length=100, null=True)),
                ('grandtotal', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(null=True)),
                ('paid', models.CharField(max_length=100, null=True)),
                ('balance', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='sales')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('partyid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sales_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, null=True)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('sale_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.salesorder')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
