# Generated by Django 3.2.19 on 2023-11-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_sales_item_salesorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_item',
            name='user',
        ),
        migrations.AddField(
            model_name='sales_item',
            name='cmp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company'),
        ),
    ]
