# Generated by Django 3.2.19 on 2023-11-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0012_auto_20231116_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='user',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details'),
        ),
    ]
