# Generated by Django 3.2.19 on 2023-11-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0013_auto_20231117_1955'),
    ]

    operations = [
        
    ]
