# Generated by Django 3.2.19 on 2023-11-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0014_auto_20231120_1117'),
    ]

    operations = [
        
    ]
