# Generated by Django 3.2.19 on 2023-11-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0015_auto_20231120_1129'),
    ]

    operations = [
        
    ]
