# Generated by Django 3.2.19 on 2023-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0016_auto_20231120_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='action',
            field=models.CharField(default='convert to invoice', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='orderno',
            field=models.IntegerField(null=True),
        ),
    ]
