# Generated by Django 3.2.19 on 2023-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0017_auto_20231120_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='partyid',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='partyname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
